config/routes.rb
Rails.application.routes.draw do

  resources :links

  get 'links/:id/comments' => 'comments#view'
  post 'links/:id/comments' => 'comments#create'

  get '/login' => "sessions#new", as: :login
  post '/login' => "sessions#create"
  delete '/login' => "sessions#destroy", as: :logout

  resources :users, only: [:new, :create]

  root 'links#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :link
end

app/models/link.rb
class Link < ActiveRecord::Base
  validates :url, format: {with: /http/}, uniqueness: true

  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :links
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user


  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def check_for_authorized_user
    unless current_user
      redirect_to login_path
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :check_for_authorized_user
  def view
    @link = Link.find(params["id"])
    @comments = Comment.where(link_id: @link.id)
    @comment = Comment.new
  end

  def create
    @link = Link.find(params["id"])
    @comment = Comment.create(body: params["comment"]["body"], link_id: @link.id, user_id: current_user.id)
    redirect_to "/links/#{@link.id}/comments"
  end

end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :check_for_authorized_user
  def index
    @links = Link.all
  end

  def new
    @link = Link.new
  end

  def create
    @link = Link.create(url: params["link"]["url"])
    redirect_to links_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.find_by(email: params["user"]["email"])

    if @user

      session[:user_id] = @user.id

      redirect_to "/links"
    else
      redirect_to(login_path)
    end
  end

  def destroy
    session[:user_id] = nil

    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.create(email: params["user"]["email"], full_name: params["user"]["full_name"])


    if @user.valid?
      redirect_to(links_path)
    else
      render :new
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/view.html.erb
<main>
<h2>Comments for <%= @link.url %></h2>

  <%= form_for @comment, url: "/links/#{@link.id}/comments" do |f| %>
    <%= f.text_field :body %>
    <%= f.submit "Comment" %>
  <% end %>

  <% @comments.each do |comment| %>
  <p>
    <%= "#{comment.user.full_name} said #{comment.body}" %>
  </p>
<% end %>

<%= link_to "Forgeddit homepage", links_path %>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Forgeddit</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
<% if session[:user_id] %>
<h4>You are currently logged in as <%= current_user.full_name %></h4>
<% end %>
</body>
</html>

app/views/links/index.html.erb
<main>
  <h1>Forgeddit</h1>
  <% @links.each do |link| %>
  <p><%= link_to link.url, "http://#{link.url}" %>
    <% @comments = Comment.where(link_id: link.id) %>
    <% @count = @comments.length %>
    <%= link_to "#{@count} Comments", "/links/#{link.id}/comments" %>
  </p>
  <% end %>
  <h3><%= link_to "Submit a new link", new_link_path %> </h3>
  <h5><%= link_to "Logout", logout_path, method: :delete %></h5>
</main>

app/views/links/new.html.erb
<main>
  <h1>Create a new link!</h1>
  <%= form_for @link, url: "/links" do |f| %>
    <%= f.label "Enter link url" %>
    <%= f.text_field :url %>
    <%= f.submit "Add link" %>
  <% end %>

</main>

app/views/users/new.html.erb
<h1>Create your Forgeddit account</h1>

<%= form_for @user, url: users_path do |f| %>
  <% @user.errors.full_messages.each do |msg| %>
    <p>
      <%= msg %>
    </p>
  <% end %>

  <%= f.label :email %>
  <%= f.text_field :email %>

  <%= f.label :full_name   %>
  <%= f.text_field :full_name  %>

  <%= f.submit %>
<% end %>